package core

func MakeConfig() map[string]any {
	return map[string]any{
		"main": map[string]any{
			"name": "MetMuseumCollection",
		},
		"feature": map[string]any{
			"test": map[string]any{
				"options": map[string]any{
					"active": false,
				},
			},
		},
		"options": map[string]any{
			"base": "https://collectionapi.metmuseum.org/public/collection/v1",
			"headers": map[string]any{
				"content-type": "application/json",
			},
			"entity": map[string]any{
				"department": map[string]any{},
				"object": map[string]any{},
				"search": map[string]any{},
			},
		},
		"entity": map[string]any{
			"department": map[string]any{
				"fields": []any{
					map[string]any{
						"active": true,
						"name": "department_id",
						"req": false,
						"type": "`$INTEGER`",
						"index$": 0,
					},
					map[string]any{
						"active": true,
						"name": "display_name",
						"req": false,
						"type": "`$STRING`",
						"index$": 1,
					},
				},
				"name": "department",
				"op": map[string]any{
					"list": map[string]any{
						"input": "data",
						"name": "list",
						"points": []any{
							map[string]any{
								"active": true,
								"args": map[string]any{},
								"method": "GET",
								"orig": "/departments",
								"parts": []any{
									"departments",
								},
								"select": map[string]any{},
								"transform": map[string]any{
									"req": "`reqdata`",
									"res": "`body`",
								},
								"index$": 0,
							},
						},
						"key$": "list",
					},
				},
				"relations": map[string]any{
					"ancestors": []any{},
				},
			},
			"object": map[string]any{
				"fields": []any{
					map[string]any{
						"active": true,
						"name": "accession_number",
						"req": false,
						"type": "`$STRING`",
						"index$": 0,
					},
					map[string]any{
						"active": true,
						"name": "accession_year",
						"req": false,
						"type": "`$STRING`",
						"index$": 1,
					},
					map[string]any{
						"active": true,
						"name": "additional_image",
						"req": false,
						"type": "`$ARRAY`",
						"index$": 2,
					},
					map[string]any{
						"active": true,
						"name": "artist_alpha_sort",
						"req": false,
						"type": "`$STRING`",
						"index$": 3,
					},
					map[string]any{
						"active": true,
						"name": "artist_begin_date",
						"req": false,
						"type": "`$STRING`",
						"index$": 4,
					},
					map[string]any{
						"active": true,
						"name": "artist_display_bio",
						"req": false,
						"type": "`$STRING`",
						"index$": 5,
					},
					map[string]any{
						"active": true,
						"name": "artist_display_name",
						"req": false,
						"type": "`$STRING`",
						"index$": 6,
					},
					map[string]any{
						"active": true,
						"name": "artist_end_date",
						"req": false,
						"type": "`$STRING`",
						"index$": 7,
					},
					map[string]any{
						"active": true,
						"name": "artist_gender",
						"req": false,
						"type": "`$STRING`",
						"index$": 8,
					},
					map[string]any{
						"active": true,
						"name": "artist_nationality",
						"req": false,
						"type": "`$STRING`",
						"index$": 9,
					},
					map[string]any{
						"active": true,
						"name": "artist_prefix",
						"req": false,
						"type": "`$STRING`",
						"index$": 10,
					},
					map[string]any{
						"active": true,
						"name": "artist_role",
						"req": false,
						"type": "`$STRING`",
						"index$": 11,
					},
					map[string]any{
						"active": true,
						"name": "artist_suffix",
						"req": false,
						"type": "`$STRING`",
						"index$": 12,
					},
					map[string]any{
						"active": true,
						"name": "artist_ulan_url",
						"req": false,
						"type": "`$STRING`",
						"index$": 13,
					},
					map[string]any{
						"active": true,
						"name": "artist_wikidata_url",
						"req": false,
						"type": "`$STRING`",
						"index$": 14,
					},
					map[string]any{
						"active": true,
						"name": "city",
						"req": false,
						"type": "`$STRING`",
						"index$": 15,
					},
					map[string]any{
						"active": true,
						"name": "classification",
						"req": false,
						"type": "`$STRING`",
						"index$": 16,
					},
					map[string]any{
						"active": true,
						"name": "constituent",
						"req": false,
						"type": "`$ARRAY`",
						"index$": 17,
					},
					map[string]any{
						"active": true,
						"name": "country",
						"req": false,
						"type": "`$STRING`",
						"index$": 18,
					},
					map[string]any{
						"active": true,
						"name": "county",
						"req": false,
						"type": "`$STRING`",
						"index$": 19,
					},
					map[string]any{
						"active": true,
						"name": "credit_line",
						"req": false,
						"type": "`$STRING`",
						"index$": 20,
					},
					map[string]any{
						"active": true,
						"name": "culture",
						"req": false,
						"type": "`$STRING`",
						"index$": 21,
					},
					map[string]any{
						"active": true,
						"name": "department",
						"req": false,
						"type": "`$STRING`",
						"index$": 22,
					},
					map[string]any{
						"active": true,
						"name": "dimension",
						"req": false,
						"type": "`$STRING`",
						"index$": 23,
					},
					map[string]any{
						"active": true,
						"name": "dimensions_parsed",
						"req": false,
						"type": "`$ARRAY`",
						"index$": 24,
					},
					map[string]any{
						"active": true,
						"name": "dynasty",
						"req": false,
						"type": "`$STRING`",
						"index$": 25,
					},
					map[string]any{
						"active": true,
						"name": "excavation",
						"req": false,
						"type": "`$STRING`",
						"index$": 26,
					},
					map[string]any{
						"active": true,
						"name": "gallery_number",
						"req": false,
						"type": "`$STRING`",
						"index$": 27,
					},
					map[string]any{
						"active": true,
						"name": "geography_type",
						"req": false,
						"type": "`$STRING`",
						"index$": 28,
					},
					map[string]any{
						"active": true,
						"name": "is_highlight",
						"req": false,
						"type": "`$BOOLEAN`",
						"index$": 29,
					},
					map[string]any{
						"active": true,
						"name": "is_public_domain",
						"req": false,
						"type": "`$BOOLEAN`",
						"index$": 30,
					},
					map[string]any{
						"active": true,
						"name": "is_timeline_work",
						"req": false,
						"type": "`$BOOLEAN`",
						"index$": 31,
					},
					map[string]any{
						"active": true,
						"name": "link_resource",
						"req": false,
						"type": "`$STRING`",
						"index$": 32,
					},
					map[string]any{
						"active": true,
						"name": "locale",
						"req": false,
						"type": "`$STRING`",
						"index$": 33,
					},
					map[string]any{
						"active": true,
						"name": "locus",
						"req": false,
						"type": "`$STRING`",
						"index$": 34,
					},
					map[string]any{
						"active": true,
						"name": "measurement",
						"req": false,
						"type": "`$ARRAY`",
						"index$": 35,
					},
					map[string]any{
						"active": true,
						"name": "medium",
						"req": false,
						"type": "`$STRING`",
						"index$": 36,
					},
					map[string]any{
						"active": true,
						"name": "metadata_date",
						"req": false,
						"type": "`$STRING`",
						"index$": 37,
					},
					map[string]any{
						"active": true,
						"name": "object_begin_date",
						"req": false,
						"type": "`$INTEGER`",
						"index$": 38,
					},
					map[string]any{
						"active": true,
						"name": "object_date",
						"req": false,
						"type": "`$STRING`",
						"index$": 39,
					},
					map[string]any{
						"active": true,
						"name": "object_end_date",
						"req": false,
						"type": "`$INTEGER`",
						"index$": 40,
					},
					map[string]any{
						"active": true,
						"name": "object_i_d",
						"req": false,
						"type": "`$ARRAY`",
						"index$": 41,
					},
					map[string]any{
						"active": true,
						"name": "object_id",
						"req": false,
						"type": "`$INTEGER`",
						"index$": 42,
					},
					map[string]any{
						"active": true,
						"name": "object_name",
						"req": false,
						"type": "`$STRING`",
						"index$": 43,
					},
					map[string]any{
						"active": true,
						"name": "object_url",
						"req": false,
						"type": "`$STRING`",
						"index$": 44,
					},
					map[string]any{
						"active": true,
						"name": "object_wikidata_url",
						"req": false,
						"type": "`$STRING`",
						"index$": 45,
					},
					map[string]any{
						"active": true,
						"name": "period",
						"req": false,
						"type": "`$STRING`",
						"index$": 46,
					},
					map[string]any{
						"active": true,
						"name": "portfolio",
						"req": false,
						"type": "`$STRING`",
						"index$": 47,
					},
					map[string]any{
						"active": true,
						"name": "primary_image",
						"req": false,
						"type": "`$STRING`",
						"index$": 48,
					},
					map[string]any{
						"active": true,
						"name": "primary_image_small",
						"req": false,
						"type": "`$STRING`",
						"index$": 49,
					},
					map[string]any{
						"active": true,
						"name": "region",
						"req": false,
						"type": "`$STRING`",
						"index$": 50,
					},
					map[string]any{
						"active": true,
						"name": "reign",
						"req": false,
						"type": "`$STRING`",
						"index$": 51,
					},
					map[string]any{
						"active": true,
						"name": "repository",
						"req": false,
						"type": "`$STRING`",
						"index$": 52,
					},
					map[string]any{
						"active": true,
						"name": "rights_and_reproduction",
						"req": false,
						"type": "`$STRING`",
						"index$": 53,
					},
					map[string]any{
						"active": true,
						"name": "river",
						"req": false,
						"type": "`$STRING`",
						"index$": 54,
					},
					map[string]any{
						"active": true,
						"name": "state",
						"req": false,
						"type": "`$STRING`",
						"index$": 55,
					},
					map[string]any{
						"active": true,
						"name": "subregion",
						"req": false,
						"type": "`$STRING`",
						"index$": 56,
					},
					map[string]any{
						"active": true,
						"name": "tag",
						"req": false,
						"type": "`$ARRAY`",
						"index$": 57,
					},
					map[string]any{
						"active": true,
						"name": "title",
						"req": false,
						"type": "`$STRING`",
						"index$": 58,
					},
					map[string]any{
						"active": true,
						"name": "total",
						"req": false,
						"type": "`$INTEGER`",
						"index$": 59,
					},
				},
				"name": "object",
				"op": map[string]any{
					"list": map[string]any{
						"input": "data",
						"name": "list",
						"points": []any{
							map[string]any{
								"active": true,
								"args": map[string]any{
									"query": []any{
										map[string]any{
											"active": true,
											"example": "1",
											"kind": "query",
											"name": "department_id",
											"orig": "department_id",
											"reqd": false,
											"type": "`$STRING`",
										},
										map[string]any{
											"active": true,
											"example": "2018-10-22",
											"kind": "query",
											"name": "metadata_date",
											"orig": "metadata_date",
											"reqd": false,
											"type": "`$STRING`",
										},
									},
								},
								"method": "GET",
								"orig": "/objects",
								"parts": []any{
									"objects",
								},
								"select": map[string]any{
									"exist": []any{
										"department_id",
										"metadata_date",
									},
								},
								"transform": map[string]any{
									"req": "`reqdata`",
									"res": "`body`",
								},
								"index$": 0,
							},
						},
						"key$": "list",
					},
					"load": map[string]any{
						"input": "data",
						"name": "load",
						"points": []any{
							map[string]any{
								"active": true,
								"args": map[string]any{
									"params": []any{
										map[string]any{
											"active": true,
											"example": 45734,
											"kind": "param",
											"name": "id",
											"orig": "object_id",
											"reqd": true,
											"type": "`$INTEGER`",
											"index$": 0,
										},
									},
								},
								"method": "GET",
								"orig": "/objects/{objectID}",
								"parts": []any{
									"objects",
									"{id}",
								},
								"rename": map[string]any{
									"param": map[string]any{
										"objectID": "id",
									},
								},
								"select": map[string]any{
									"exist": []any{
										"id",
									},
								},
								"transform": map[string]any{
									"req": "`reqdata`",
									"res": "`body`",
								},
								"index$": 0,
							},
						},
						"key$": "load",
					},
				},
				"relations": map[string]any{
					"ancestors": []any{},
				},
			},
			"search": map[string]any{
				"fields": []any{
					map[string]any{
						"active": true,
						"name": "object_i_d",
						"req": false,
						"type": "`$ARRAY`",
						"index$": 0,
					},
					map[string]any{
						"active": true,
						"name": "total",
						"req": false,
						"type": "`$INTEGER`",
						"index$": 1,
					},
				},
				"name": "search",
				"op": map[string]any{
					"list": map[string]any{
						"input": "data",
						"name": "list",
						"points": []any{
							map[string]any{
								"active": true,
								"args": map[string]any{
									"query": []any{
										map[string]any{
											"active": true,
											"example": true,
											"kind": "query",
											"name": "artist_or_culture",
											"orig": "artist_or_culture",
											"reqd": false,
											"type": "`$BOOLEAN`",
										},
										map[string]any{
											"active": true,
											"example": 1800,
											"kind": "query",
											"name": "date_begin",
											"orig": "date_begin",
											"reqd": false,
											"type": "`$INTEGER`",
										},
										map[string]any{
											"active": true,
											"example": 1900,
											"kind": "query",
											"name": "date_end",
											"orig": "date_end",
											"reqd": false,
											"type": "`$INTEGER`",
										},
										map[string]any{
											"active": true,
											"example": 11,
											"kind": "query",
											"name": "department_id",
											"orig": "department_id",
											"reqd": false,
											"type": "`$INTEGER`",
										},
										map[string]any{
											"active": true,
											"example": "Europe",
											"kind": "query",
											"name": "geo_location",
											"orig": "geo_location",
											"reqd": false,
											"type": "`$STRING`",
										},
										map[string]any{
											"active": true,
											"example": true,
											"kind": "query",
											"name": "has_image",
											"orig": "has_image",
											"reqd": false,
											"type": "`$BOOLEAN`",
										},
										map[string]any{
											"active": true,
											"example": true,
											"kind": "query",
											"name": "is_highlight",
											"orig": "is_highlight",
											"reqd": false,
											"type": "`$BOOLEAN`",
										},
										map[string]any{
											"active": true,
											"example": true,
											"kind": "query",
											"name": "is_on_view",
											"orig": "is_on_view",
											"reqd": false,
											"type": "`$BOOLEAN`",
										},
										map[string]any{
											"active": true,
											"example": "Paintings",
											"kind": "query",
											"name": "medium",
											"orig": "medium",
											"reqd": false,
											"type": "`$STRING`",
										},
										map[string]any{
											"active": true,
											"example": "sunflowers",
											"kind": "query",
											"name": "q",
											"orig": "q",
											"reqd": false,
											"type": "`$STRING`",
										},
										map[string]any{
											"active": true,
											"example": true,
											"kind": "query",
											"name": "tag",
											"orig": "tag",
											"reqd": false,
											"type": "`$BOOLEAN`",
										},
										map[string]any{
											"active": true,
											"example": true,
											"kind": "query",
											"name": "title",
											"orig": "title",
											"reqd": false,
											"type": "`$BOOLEAN`",
										},
									},
								},
								"method": "GET",
								"orig": "/search",
								"parts": []any{
									"search",
								},
								"select": map[string]any{
									"exist": []any{
										"artist_or_culture",
										"date_begin",
										"date_end",
										"department_id",
										"geo_location",
										"has_image",
										"is_highlight",
										"is_on_view",
										"medium",
										"q",
										"tag",
										"title",
									},
								},
								"transform": map[string]any{
									"req": "`reqdata`",
									"res": "`body`",
								},
								"index$": 0,
							},
						},
						"key$": "list",
					},
				},
				"relations": map[string]any{
					"ancestors": []any{},
				},
			},
		},
	}
}

func makeFeature(name string) Feature {
	switch name {
	case "test":
		if NewTestFeatureFunc != nil {
			return NewTestFeatureFunc()
		}
	default:
		if NewBaseFeatureFunc != nil {
			return NewBaseFeatureFunc()
		}
	}
	return nil
}
