# MetMuseumCollection SDK configuration


def make_config():
    return {
        "main": {
            "name": "MetMuseumCollection",
        },
        "feature": {
            "test": {
        "options": {
          "active": False,
        },
      },
        },
        "options": {
            "base": "https://collectionapi.metmuseum.org/public/collection/v1",
            "headers": {
        "content-type": "application/json",
      },
            "entity": {
                "department": {},
                "object": {},
                "search": {},
            },
        },
        "entity": {
      "department": {
        "fields": [
          {
            "active": True,
            "name": "department_id",
            "req": False,
            "type": "`$INTEGER`",
            "index$": 0,
          },
          {
            "active": True,
            "name": "display_name",
            "req": False,
            "type": "`$STRING`",
            "index$": 1,
          },
        ],
        "name": "department",
        "op": {
          "list": {
            "input": "data",
            "name": "list",
            "points": [
              {
                "active": True,
                "args": {},
                "method": "GET",
                "orig": "/departments",
                "parts": [
                  "departments",
                ],
                "select": {},
                "transform": {
                  "req": "`reqdata`",
                  "res": "`body`",
                },
                "index$": 0,
              },
            ],
            "key$": "list",
          },
        },
        "relations": {
          "ancestors": [],
        },
      },
      "object": {
        "fields": [
          {
            "active": True,
            "name": "accession_number",
            "req": False,
            "type": "`$STRING`",
            "index$": 0,
          },
          {
            "active": True,
            "name": "accession_year",
            "req": False,
            "type": "`$STRING`",
            "index$": 1,
          },
          {
            "active": True,
            "name": "additional_image",
            "req": False,
            "type": "`$ARRAY`",
            "index$": 2,
          },
          {
            "active": True,
            "name": "artist_alpha_sort",
            "req": False,
            "type": "`$STRING`",
            "index$": 3,
          },
          {
            "active": True,
            "name": "artist_begin_date",
            "req": False,
            "type": "`$STRING`",
            "index$": 4,
          },
          {
            "active": True,
            "name": "artist_display_bio",
            "req": False,
            "type": "`$STRING`",
            "index$": 5,
          },
          {
            "active": True,
            "name": "artist_display_name",
            "req": False,
            "type": "`$STRING`",
            "index$": 6,
          },
          {
            "active": True,
            "name": "artist_end_date",
            "req": False,
            "type": "`$STRING`",
            "index$": 7,
          },
          {
            "active": True,
            "name": "artist_gender",
            "req": False,
            "type": "`$STRING`",
            "index$": 8,
          },
          {
            "active": True,
            "name": "artist_nationality",
            "req": False,
            "type": "`$STRING`",
            "index$": 9,
          },
          {
            "active": True,
            "name": "artist_prefix",
            "req": False,
            "type": "`$STRING`",
            "index$": 10,
          },
          {
            "active": True,
            "name": "artist_role",
            "req": False,
            "type": "`$STRING`",
            "index$": 11,
          },
          {
            "active": True,
            "name": "artist_suffix",
            "req": False,
            "type": "`$STRING`",
            "index$": 12,
          },
          {
            "active": True,
            "name": "artist_ulan_url",
            "req": False,
            "type": "`$STRING`",
            "index$": 13,
          },
          {
            "active": True,
            "name": "artist_wikidata_url",
            "req": False,
            "type": "`$STRING`",
            "index$": 14,
          },
          {
            "active": True,
            "name": "city",
            "req": False,
            "type": "`$STRING`",
            "index$": 15,
          },
          {
            "active": True,
            "name": "classification",
            "req": False,
            "type": "`$STRING`",
            "index$": 16,
          },
          {
            "active": True,
            "name": "constituent",
            "req": False,
            "type": "`$ARRAY`",
            "index$": 17,
          },
          {
            "active": True,
            "name": "country",
            "req": False,
            "type": "`$STRING`",
            "index$": 18,
          },
          {
            "active": True,
            "name": "county",
            "req": False,
            "type": "`$STRING`",
            "index$": 19,
          },
          {
            "active": True,
            "name": "credit_line",
            "req": False,
            "type": "`$STRING`",
            "index$": 20,
          },
          {
            "active": True,
            "name": "culture",
            "req": False,
            "type": "`$STRING`",
            "index$": 21,
          },
          {
            "active": True,
            "name": "department",
            "req": False,
            "type": "`$STRING`",
            "index$": 22,
          },
          {
            "active": True,
            "name": "dimension",
            "req": False,
            "type": "`$STRING`",
            "index$": 23,
          },
          {
            "active": True,
            "name": "dimensions_parsed",
            "req": False,
            "type": "`$ARRAY`",
            "index$": 24,
          },
          {
            "active": True,
            "name": "dynasty",
            "req": False,
            "type": "`$STRING`",
            "index$": 25,
          },
          {
            "active": True,
            "name": "excavation",
            "req": False,
            "type": "`$STRING`",
            "index$": 26,
          },
          {
            "active": True,
            "name": "gallery_number",
            "req": False,
            "type": "`$STRING`",
            "index$": 27,
          },
          {
            "active": True,
            "name": "geography_type",
            "req": False,
            "type": "`$STRING`",
            "index$": 28,
          },
          {
            "active": True,
            "name": "is_highlight",
            "req": False,
            "type": "`$BOOLEAN`",
            "index$": 29,
          },
          {
            "active": True,
            "name": "is_public_domain",
            "req": False,
            "type": "`$BOOLEAN`",
            "index$": 30,
          },
          {
            "active": True,
            "name": "is_timeline_work",
            "req": False,
            "type": "`$BOOLEAN`",
            "index$": 31,
          },
          {
            "active": True,
            "name": "link_resource",
            "req": False,
            "type": "`$STRING`",
            "index$": 32,
          },
          {
            "active": True,
            "name": "locale",
            "req": False,
            "type": "`$STRING`",
            "index$": 33,
          },
          {
            "active": True,
            "name": "locus",
            "req": False,
            "type": "`$STRING`",
            "index$": 34,
          },
          {
            "active": True,
            "name": "measurement",
            "req": False,
            "type": "`$ARRAY`",
            "index$": 35,
          },
          {
            "active": True,
            "name": "medium",
            "req": False,
            "type": "`$STRING`",
            "index$": 36,
          },
          {
            "active": True,
            "name": "metadata_date",
            "req": False,
            "type": "`$STRING`",
            "index$": 37,
          },
          {
            "active": True,
            "name": "object_begin_date",
            "req": False,
            "type": "`$INTEGER`",
            "index$": 38,
          },
          {
            "active": True,
            "name": "object_date",
            "req": False,
            "type": "`$STRING`",
            "index$": 39,
          },
          {
            "active": True,
            "name": "object_end_date",
            "req": False,
            "type": "`$INTEGER`",
            "index$": 40,
          },
          {
            "active": True,
            "name": "object_i_d",
            "req": False,
            "type": "`$ARRAY`",
            "index$": 41,
          },
          {
            "active": True,
            "name": "object_id",
            "req": False,
            "type": "`$INTEGER`",
            "index$": 42,
          },
          {
            "active": True,
            "name": "object_name",
            "req": False,
            "type": "`$STRING`",
            "index$": 43,
          },
          {
            "active": True,
            "name": "object_url",
            "req": False,
            "type": "`$STRING`",
            "index$": 44,
          },
          {
            "active": True,
            "name": "object_wikidata_url",
            "req": False,
            "type": "`$STRING`",
            "index$": 45,
          },
          {
            "active": True,
            "name": "period",
            "req": False,
            "type": "`$STRING`",
            "index$": 46,
          },
          {
            "active": True,
            "name": "portfolio",
            "req": False,
            "type": "`$STRING`",
            "index$": 47,
          },
          {
            "active": True,
            "name": "primary_image",
            "req": False,
            "type": "`$STRING`",
            "index$": 48,
          },
          {
            "active": True,
            "name": "primary_image_small",
            "req": False,
            "type": "`$STRING`",
            "index$": 49,
          },
          {
            "active": True,
            "name": "region",
            "req": False,
            "type": "`$STRING`",
            "index$": 50,
          },
          {
            "active": True,
            "name": "reign",
            "req": False,
            "type": "`$STRING`",
            "index$": 51,
          },
          {
            "active": True,
            "name": "repository",
            "req": False,
            "type": "`$STRING`",
            "index$": 52,
          },
          {
            "active": True,
            "name": "rights_and_reproduction",
            "req": False,
            "type": "`$STRING`",
            "index$": 53,
          },
          {
            "active": True,
            "name": "river",
            "req": False,
            "type": "`$STRING`",
            "index$": 54,
          },
          {
            "active": True,
            "name": "state",
            "req": False,
            "type": "`$STRING`",
            "index$": 55,
          },
          {
            "active": True,
            "name": "subregion",
            "req": False,
            "type": "`$STRING`",
            "index$": 56,
          },
          {
            "active": True,
            "name": "tag",
            "req": False,
            "type": "`$ARRAY`",
            "index$": 57,
          },
          {
            "active": True,
            "name": "title",
            "req": False,
            "type": "`$STRING`",
            "index$": 58,
          },
          {
            "active": True,
            "name": "total",
            "req": False,
            "type": "`$INTEGER`",
            "index$": 59,
          },
        ],
        "name": "object",
        "op": {
          "list": {
            "input": "data",
            "name": "list",
            "points": [
              {
                "active": True,
                "args": {
                  "query": [
                    {
                      "active": True,
                      "example": "1",
                      "kind": "query",
                      "name": "department_id",
                      "orig": "department_id",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "example": "2018-10-22",
                      "kind": "query",
                      "name": "metadata_date",
                      "orig": "metadata_date",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                  ],
                },
                "method": "GET",
                "orig": "/objects",
                "parts": [
                  "objects",
                ],
                "select": {
                  "exist": [
                    "department_id",
                    "metadata_date",
                  ],
                },
                "transform": {
                  "req": "`reqdata`",
                  "res": "`body`",
                },
                "index$": 0,
              },
            ],
            "key$": "list",
          },
          "load": {
            "input": "data",
            "name": "load",
            "points": [
              {
                "active": True,
                "args": {
                  "params": [
                    {
                      "active": True,
                      "example": 45734,
                      "kind": "param",
                      "name": "id",
                      "orig": "object_id",
                      "reqd": True,
                      "type": "`$INTEGER`",
                      "index$": 0,
                    },
                  ],
                },
                "method": "GET",
                "orig": "/objects/{objectID}",
                "parts": [
                  "objects",
                  "{id}",
                ],
                "rename": {
                  "param": {
                    "objectID": "id",
                  },
                },
                "select": {
                  "exist": [
                    "id",
                  ],
                },
                "transform": {
                  "req": "`reqdata`",
                  "res": "`body`",
                },
                "index$": 0,
              },
            ],
            "key$": "load",
          },
        },
        "relations": {
          "ancestors": [],
        },
      },
      "search": {
        "fields": [
          {
            "active": True,
            "name": "object_i_d",
            "req": False,
            "type": "`$ARRAY`",
            "index$": 0,
          },
          {
            "active": True,
            "name": "total",
            "req": False,
            "type": "`$INTEGER`",
            "index$": 1,
          },
        ],
        "name": "search",
        "op": {
          "list": {
            "input": "data",
            "name": "list",
            "points": [
              {
                "active": True,
                "args": {
                  "query": [
                    {
                      "active": True,
                      "example": True,
                      "kind": "query",
                      "name": "artist_or_culture",
                      "orig": "artist_or_culture",
                      "reqd": False,
                      "type": "`$BOOLEAN`",
                    },
                    {
                      "active": True,
                      "example": 1800,
                      "kind": "query",
                      "name": "date_begin",
                      "orig": "date_begin",
                      "reqd": False,
                      "type": "`$INTEGER`",
                    },
                    {
                      "active": True,
                      "example": 1900,
                      "kind": "query",
                      "name": "date_end",
                      "orig": "date_end",
                      "reqd": False,
                      "type": "`$INTEGER`",
                    },
                    {
                      "active": True,
                      "example": 11,
                      "kind": "query",
                      "name": "department_id",
                      "orig": "department_id",
                      "reqd": False,
                      "type": "`$INTEGER`",
                    },
                    {
                      "active": True,
                      "example": "Europe",
                      "kind": "query",
                      "name": "geo_location",
                      "orig": "geo_location",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "example": True,
                      "kind": "query",
                      "name": "has_image",
                      "orig": "has_image",
                      "reqd": False,
                      "type": "`$BOOLEAN`",
                    },
                    {
                      "active": True,
                      "example": True,
                      "kind": "query",
                      "name": "is_highlight",
                      "orig": "is_highlight",
                      "reqd": False,
                      "type": "`$BOOLEAN`",
                    },
                    {
                      "active": True,
                      "example": True,
                      "kind": "query",
                      "name": "is_on_view",
                      "orig": "is_on_view",
                      "reqd": False,
                      "type": "`$BOOLEAN`",
                    },
                    {
                      "active": True,
                      "example": "Paintings",
                      "kind": "query",
                      "name": "medium",
                      "orig": "medium",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "example": "sunflowers",
                      "kind": "query",
                      "name": "q",
                      "orig": "q",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "example": True,
                      "kind": "query",
                      "name": "tag",
                      "orig": "tag",
                      "reqd": False,
                      "type": "`$BOOLEAN`",
                    },
                    {
                      "active": True,
                      "example": True,
                      "kind": "query",
                      "name": "title",
                      "orig": "title",
                      "reqd": False,
                      "type": "`$BOOLEAN`",
                    },
                  ],
                },
                "method": "GET",
                "orig": "/search",
                "parts": [
                  "search",
                ],
                "select": {
                  "exist": [
                    "artist_or_culture",
                    "date_begin",
                    "date_end",
                    "department_id",
                    "geo_location",
                    "has_image",
                    "is_highlight",
                    "is_on_view",
                    "medium",
                    "q",
                    "tag",
                    "title",
                  ],
                },
                "transform": {
                  "req": "`reqdata`",
                  "res": "`body`",
                },
                "index$": 0,
              },
            ],
            "key$": "list",
          },
        },
        "relations": {
          "ancestors": [],
        },
      },
    },
    }
